version: 2
plan:
    project-key: SFX
    key: SFX
    name: NodeJs
stages:
  - Build node_modules:
    - build
  - Build Docker:
    - build_docker
  - deploy to ecs:
    - deploy_ecs
build:
  tasks:
    - script:
        - npm install
  requirements:
    - npm
build_docker:
  tasks:
    - script:
        - whoami
        - echo 'Docker Build'
        - docker build -t nodeapp:latest .
        - docker login docker.io
        - docker tag nodeapp:latest docker.io/mithunlatiff/sample-node:latest
        - docker push docker.io/mithunlatiff/sample-node:latest
        - docker tag nodeapp:latest docker.io/mithunlatiff/sample-node:${bamboo.buildNumber}
        - docker push docker.io/mithunlatiff/sample-node:${bamboo.buildNumber}
deploy_ecs:
  tasks:
    - script:
        - mkdir -p ~/aws-cli
        - mkdir -p ~/.aws
        - echo -e "[default]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials 
        - export AWS_DEFAULT_PROFILE=default
        - export BUILD_ID=${bamboo.buildNumber}
        - export repo=sample-node:latest
        - aws s3 ls
  docker:
    image: amazon/aws-cli:latest
    docker-run-arguments:
    - --entrypoint=/usr/bin/env