version: 2
plan:
    project-key: SSX
    key: SSX
    name: NodeJs
stages:
  - Build node_modules:
    - build
  - Build Docker:
    - build_docker
  - deploy to ecs:
    - deploy_ecs
build:
  tasks:
    - script:
        - npm install
  requirements:
    - npm
build_docker:
  tasks:
    - script:
        - whoami
        - echo 'Docker Build'
        - docker build -t nodeapp:latest .
        - docker login docker.io
        - docker tag nodeapp:latest docker.io/mithunlatiff/sample-node:latest
        - docker push docker.io/mithunlatiff/sample-node:latest
        - docker tag nodeapp:latest docker.io/mithunlatiff/sample-node:${bamboo.buildNumber}
        - docker push docker.io/mithunlatiff/sample-node:${bamboo.buildNumber}
deploy_ecs:
  tasks:
    # agent preinstalled with AWS CLI
    - script:
        - whoami
        - export AWS_ACCESS_KEY_ID=$bamboo_AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$bamboo_AWS_SECRET_ACCESS_KEY
        - export AWS_DEFAULT_REGION=ap-southeast-1
        - export BUILD_ID=${bamboo.buildNumber}
        - export repo=sample-node:latest
        - aws s3 ls