version: 2
plan:
    project-key: NEXT
    key: NEXT
    name: NodeJs
stages:
  - Build node_modules:
    - build
  - Build Docker:
    - build_docker
build:
  tasks:
    - script:
        - npm install
  requirements:
    - npm
  artifacts:
    - name: node_modules
      pattern: node_modules/
build_docker:
  tasks:
    - script:
        - whoami
        - echo 'Docker Build'
        - docker build -t nodeapp:latest .
        - docker login docker.io
        - docker tag nodeapp:latest docker.io/mithunlatiff/sample-node:latest
        - docker push docker.io/mithunlatiff/sample-node:latest
        - docker tag nodeapp:latest docker.io/mithunlatiff/sample-node:${bamboo.buildNumber}
        - docker push docker.io/mithunlatiff/sample-node:${bamboo.buildNumber}
