version: 2
plan:
    project-key: MYP
    key: MYP
    name: NodeJs
stages:
  - Build node_modules:
    - build
  - Build Docker:
    - build_docker
build:
  tasks:
    - script:
        - npm install
  requirements:
    - npm
  artifacts:
    - name: node_modules
      pattern: node_modules/
build_docker:
  tasks:
    - script:
        - whoami
        - echo 'Docker Build'
        - docker build -t nodeapp:latest .
        - docker login -u ${bamboo.dockerusername} -p ${bamboo.dockersecret} docker.io/mithunlatiff
        - docker tag nodeapp:latest mithunlatiff/sample-node:latest
        - docker push mithunlatiff/sample-node:latest
        - docker tag nodeapp:latest mithunlatiff/sample-node:${bamboo.buildNumber}
        - docker push mithunlatiff/sample-node:${bamboo.buildNumber}
